import os
import sys

def generate_md_report(report_dir, timestamp):
    report_file = os.path.join(report_dir, f"report_{timestamp}.md")
    
    with open(report_file, 'w') as md_file:
        md_file.write(f"# System Monitoring Report ({timestamp}) , GENERATED BY PYTHON !!\n")

        for file in os.listdir(report_dir):
            if file.endswith(f"_{timestamp}.log"):
                section = file.replace(f"_{timestamp}.log", "")
                md_file.write(f"\n## {section.capitalize()} ##\n\n")

                with open(os.path.join(report_dir, file), 'r') as log_file:
                    md_file.write(log_file.read())

    print(f"Markdown report generated at: {report_file}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python generate_md_report.py <report_directory> <timestamp>")
        sys.exit(1)

    report_dir = sys.argv[1]
    timestamp = sys.argv[2]
    
    generate_md_report(report_dir, timestamp)
